export const departments = [
  {
    name: "Ricerca",
    count: 12,
    day: "Lunedì",
    icon: "search",
    color: "sage",
    description: "Troviamo le aziende giuste.",
    task: "Analisi di aziende e segnali di mercato",
    metric: "248 aziende trovate",
    progress: 88,
  },
  {
    name: "Qualifica",
    count: 9,
    day: "Martedì",
    icon: "shield",
    color: "blue",
    description: "Solo contatti che contano.",
    task: "Verifica settore, dimensioni e decisori",
    metric: "186 lead qualificati",
    progress: 75,
  },
  {
    name: "Messaggi",
    count: 15,
    day: "Mercoledì",
    icon: "message",
    color: "purple",
    description: "Ogni messaggio, personale.",
    task: "Personalizzazione e controllo del tono",
    metric: "124 messaggi preparati",
    progress: 64,
  },
  {
    name: "Risposte",
    count: 8,
    day: "Giovedì",
    icon: "reply",
    color: "peach",
    description: "La conversazione continua.",
    task: "Gestione risposte e follow-up a 3 giorni",
    metric: "38 conversazioni aperte",
    progress: 56,
  },
  {
    name: "Agenda",
    count: 5,
    day: "Venerdì",
    icon: "calendar",
    color: "yellow",
    description: "Tu devi solo esserci.",
    task: "Coordinamento disponibilità e conferme",
    metric: "12 chiamate in agenda",
    progress: 72,
  },
  {
    name: "Nutrimento",
    count: 7,
    day: "Sabato",
    icon: "leaf",
    color: "pink",
    description: "Il valore, prima della vendita.",
    task: "Contenuti utili ogni due settimane",
    metric: "64 relazioni coltivate",
    progress: 46,
  },
  {
    name: "Apprendimento",
    count: 7,
    day: "Domenica",
    icon: "sparkles",
    color: "sky",
    description: "Ogni settimana, più precisi.",
    task: "Analisi di settori, messaggi e orari",
    metric: "8 insight individuati",
    progress: 82,
  },
  {
    name: "Orchestrazione",
    count: 4,
    day: "Ogni giorno",
    icon: "network",
    color: "stone",
    description: "Tutto al posto giusto.",
    task: "Assegnazioni, limiti e controllo anomalie",
    metric: "Tutti i sistemi allineati",
    progress: 100,
  },
];
export const initialLeads = [
  {
    id: 1,
    company: "Studio Forma",
    initials: "SF",
    sector: "Architettura & Design",
    name: "Giulia Moretti",
    role: "Founder",
    city: "Milano",
    score: 96,
    status: "Appuntamento",
    color: "sage",
    email: "giulia@studioforma.example",
  },
  {
    id: 2,
    company: "Nexora Digital",
    initials: "N",
    sector: "Software & Tecnologia",
    name: "Marco Rinaldi",
    role: "CEO",
    city: "Bologna",
    score: 94,
    status: "In conversazione",
    color: "purple",
    email: "marco@nexora.example",
  },
  {
    id: 3,
    company: "VerdeVivo",
    initials: "vv",
    sector: "Sostenibilità",
    name: "Elena Conti",
    role: "Direttrice commerciale",
    city: "Torino",
    score: 91,
    status: "Qualificato",
    color: "sage",
    email: "elena@verdevivo.example",
  },
  {
    id: 4,
    company: "Officina 32",
    initials: "O32",
    sector: "Manifattura",
    name: "Andrea Ferri",
    role: "Titolare",
    city: "Brescia",
    score: 89,
    status: "Messaggio pronto",
    color: "peach",
    email: "andrea@officina32.example",
  },
  {
    id: 5,
    company: "Linea Studio",
    initials: "ls",
    sector: "Marketing & Comunicazione",
    name: "Sara Ricci",
    role: "Co-founder",
    city: "Roma",
    score: 87,
    status: "In conversazione",
    color: "blue",
    email: "sara@linea.example",
  },
  {
    id: 6,
    company: "Alba Consulting",
    initials: "ac",
    sector: "Consulenza",
    name: "Luca Bianchi",
    role: "Partner",
    city: "Firenze",
    score: 84,
    status: "Da qualificare",
    color: "yellow",
    email: "luca@alba.example",
  },
];
export function filterLeads(leads, query = "", status = "Tutti") {
  const text = query.toLocaleLowerCase("it").trim();
  return leads.filter(
    (l) =>
      (status === "Tutti" || l.status === status) &&
      `${l.company} ${l.name} ${l.city} ${l.sector}`
        .toLocaleLowerCase("it")
        .includes(text),
  );
}
export function reportLines(leads, campaign) {
  return [
    "AGENTE — Report settimanale · simulazione",
    `Campagna: ${campaign.name}`,
    "67 agenti coordinati in 8 reparti.",
    "Ricerca: 248 aziende individuate nel dataset dimostrativo.",
    "Qualifica: 186 aziende compatibili con il profilo ideale.",
    "Messaggi: 124 bozze personalizzate, soggette a controllo del tono.",
    "Risposte: 38 conversazioni simulate; follow-up non prima di 3 giorni.",
    `Agenda: ${leads.filter((l) => l.status === "Appuntamento").length} appuntamenti nel campione visibile; nessuna prenotazione reale.`,
    "Nutrimento: 64 contatti dimostrativi; cadenza minima di 14 giorni.",
    "Prossimo passo: collegare fonti autorizzate, email e calendario prima di attivare il servizio.",
  ];
}
